dnd/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace dnd.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

dnd/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using dnd.Data.Models;
using dnd.Utils;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace dnd.Pages
{
    public class IndexModel : PageModel
    {
        private readonly IHttpContextAccessor _http;
        private ISession _session => _http.HttpContext.Session;

        public IndexModel(IHttpContextAccessor http)
        {
            _http = http;
        }

        public void OnGet()
        {
            var user = new User
            {
                Id = 1,
                Name = "Gil",
                Password = "gillovespoo"
            };
            _session.SetObject(SessionKeys.User, user);
        }
    }
}

dnd/Pages/Login.cshtml.cs
using System.Linq;
using dnd.BusinessLogic;
using dnd.Data;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace dnd.Pages
{
    public class Login : PageModel
    {
        private readonly ISecurityManager _security;

        public Login(ISecurityManager security)
        {
            _security = security;
        }

        public ActionResult OnPostLogin(string name, string password)
        {
            var user = _security.Login(name, password);
            
            return user != null ? Redirect("/Room-List") : null;
        }
    }
}

dnd/Pages/Room-List.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using dnd.BusinessLogic;
using dnd.Data;
using dnd.Data.Models;
using dnd.Utils;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace dnd.Pages
{
    public class RoomListModel : PageModel
    {
        private readonly DnDContext _context;
        private readonly IHttpContextAccessor _http;
        private ISession _session => _http.HttpContext.Session;
        private readonly ISecurityManager _security;
        public readonly IEnumerable<Room> Rooms;

        public RoomListModel(DnDContext context, IHttpContextAccessor http, ISecurityManager security)
        {
            _context = context;
            _http = http;
            _security = security;
            Rooms = _context.Rooms.Select(x => x).ToList();
        }

        public IActionResult OnGet()
        {
            return !_security.IsLoggedIn() ? Redirect("/login") : null;
        }
    }
}

dnd/Pages/Rooms.cshtml.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using dnd.BusinessLogic;
using dnd.Data;
using dnd.Data.Models;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace dnd.Pages
{
    public class Rooms : PageModel
    {
        private readonly DnDContext _context;
        
        public Rooms(DnDContext context)
        {
            _context = context;
        }
        public async Task OnPostToggle(int id, bool inCombat)
        {
            var newCombatStatus = !inCombat;
            (await _context.Rooms.FindAsync(id)).InCombat = newCombatStatus;
            var characters = _context.Characters.Where(c => c.RoomId == id);
            if (!newCombatStatus)
                await characters.ForEachAsync(c =>
                {
                    c.Initiative = 0;
                    c.TurnNumber = 0;
                });
            else
                await characters.ForEachAsync(c => c.Initiative = DiceRoller.RollD20(c.Dex));
            await _context.SaveChangesAsync();
        }

        public async Task OnPostTurnTaken(int roomId, int characterId)
        {
            (await _context.Characters.FindAsync(characterId)).TurnNumber++;
            await _context.SaveChangesAsync();
        }
        
        public Room GetRoom(string id)
        {
            return _context.Rooms
                .Include(r => r.Characters)
                .ThenInclude(c => c.User)
                .First(room => room.Id == Convert.ToInt32(id));
        }
    }
}

dnd/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

dnd/Pages/Login.cshtml
@page
@model dnd.Pages.Login

<h1>Login</h1>

<form method="post" asp-page-handler="login">
    <input type="text" name="name">
    <input type="password" name="password">
    <button type="submit">LOGIN</button>
</form>

dnd/Pages/Room-List.cshtml
@page
@model dnd.Pages.RoomListModel
@{
    ViewData["Title"] = "Rooms";
}

<h1>@ViewData["Title"]</h1>

<p>A list of available rooms.</p>
<ul>
    @foreach (var room in Model.Rooms)
    {
        <li><a asp-page="/Rooms" asp-route-id="@room.Id">@room.Name</a></li>     
    }
</ul>

dnd/Pages/Rooms.cshtml
@page "{id}"
@model dnd.Pages.Rooms
@{
    var id = RouteData.Values["id"].ToString();
    var room = Model.GetRoom(id);
}
<h1>@room.Name</h1>
<form method="post" asp-page-handler="toggle"
      asp-route-id="@RouteData.Values["id"]"
      asp-route-inCombat="@room.InCombat">
    @if (room.InCombat)
    {
        <button class="btn btn-danger">End Combat</button>
    }
    else
    {
        <button class="btn btn-success">Begin Combat</button>
    }
</form>
<table class="table">
    <thead>
    <tr>
        <th scope="col">Character</th>
        <th scope="col">Player</th>
        <th scope="col">Dex</th>
        <th scope="col">Initiative</th>
        <th scope="col"/>
    </tr>
    </thead>
    <tbody>
    @foreach (var character in @room.Characters.OrderBy(c => c.TurnNumber).ThenByDescending(c => c.Initiative))
    {
        <tr>
            <td>@character.Name</td>
            <td>@character.User.Name</td>
            <td>@character.Dex</td>
            <td>@character.Initiative</td>
            <td>
                <form method="post" asp-page-handler="turnTaken"
                      asp-route-roomId="@room.Id"
                      asp-route-characterId="@character.Id">
                    <button class="btn btn-sm btn-info">✔</button>
                </form>
            </td>
        </tr>
    }
    </tbody>
</table>

dnd/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - dnd</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css"/>
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-page="/Index">dnd</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-page="/Room-List">Rooms</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-page="/Login">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-page="/Login">Login</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <partial name="_CookieConsentPartial"/>
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2019 - dnd - <a asp-area="" asp-page="/Privacy">Privacy</a>
    </div>
</footer>

<environment include="Development">
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
</environment>
<environment exclude="Development">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery"
            crossorigin="anonymous"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
            asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
            crossorigin="anonymous"
            integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
</environment>
<script src="~/js/site.js" asp-append-version="true"></script>

@RenderSection("Scripts", required: false)
</body>
</html>